#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Feb 14 15:42:15 +0800 2021
# SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_11 processing_system7_vip_v1_0_13 xil_defaultlib generic_baseblocks_v2_1_0 axi_register_slice_v2_1_25 fifo_generator_v13_2_6 axi_data_fifo_v2_1_24 axi_crossbar_v2_1_26 axi_protocol_converter_v2_1_25 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 axi_clock_converter_v2_1_24 blk_mem_gen_v8_4_5 axi_dwidth_converter_v2_1_25)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2021.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "D:/vivado/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/vivado/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/vivado/Vivado/2021.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/vivado/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/vivado/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/vivado/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/vivado/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/vivado/Vivado/2021.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/vivado/Vivado/2021.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "D:/vivado/Vivado/2021.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/vivado/Vivado/2021.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/vivado/Vivado/2021.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_11 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/63b7/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b9ab/hdl/verilog/pool_ama_addmuladd_6s_6s_6s_17s_17_4_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b9ab/hdl/verilog/pool_control_s_axi.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b9ab/hdl/verilog/pool_flow_control_loop_pipe_sequential_init.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b9ab/hdl/verilog/pool_gmem_m_axi.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b9ab/hdl/verilog/pool_mul_5ns_6s_11_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b9ab/hdl/verilog/pool_mul_6s_6s_12_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b9ab/hdl/verilog/pool_mul_8ns_8ns_16_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b9ab/hdl/verilog/pool_mul_8s_8s_16_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b9ab/hdl/verilog/pool_mul_mul_11s_6s_16_4_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b9ab/hdl/verilog/pool_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b9ab/hdl/verilog/pool_sdiv_7s_8s_6_11_seq_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b9ab/hdl/verilog/pool_sdiv_19ns_16s_18_23_seq_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b9ab/hdl/verilog/pool.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_pool_0_0/sim/design_1_pool_0_0.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/75f8/hdl/verilog/matmul_control_s_axi.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/75f8/hdl/verilog/matmul_flow_control_loop_pipe_sequential_init.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/75f8/hdl/verilog/matmul_gmem_m_axi.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/75f8/hdl/verilog/matmul_mac_muladd_7ns_8s_7ns_15_4_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/75f8/hdl/verilog/matmul_mac_muladd_8s_8s_18s_18_4_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/75f8/hdl/verilog/matmul_matmul_Pipeline_VITIS_LOOP_16_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/75f8/hdl/verilog/matmul_matmul_Pipeline_VITIS_LOOP_20_2_VITIS_LOOP_21_3_VITIS_LOOP_22_4.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/75f8/hdl/verilog/matmul_mul_7ns_8ns_15_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/75f8/hdl/verilog/matmul_mul_7ns_8s_15_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/75f8/hdl/verilog/matmul_mul_8ns_8ns_16_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/75f8/hdl/verilog/matmul_mul_mul_8ns_16ns_24_4_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/75f8/hdl/verilog/matmul.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_matmul_0_0/sim/design_1_matmul_0_0.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/069d/hdl/verilog/mat_add_control_s_axi.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/069d/hdl/verilog/mat_add_gmem_m_axi.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/069d/hdl/verilog/mat_add.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mat_add_0_0/sim/design_1_mat_add_0_0.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_control_s_axi.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_flow_control_loop_pipe_sequential_init.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_gmem_m_axi.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_im2col_mat_Pipeline_VITIS_LOOP_56_7.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mac_muladd_2ns_3ns_26ns_26_4_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mat_in_pad_V_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mul_3ns_3ns_6_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mul_3ns_32ns_35_2_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mul_5ns_6ns_11_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mul_6ns_3ns_9_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mul_6ns_35ns_41_2_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mul_6s_6s_12_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mul_7s_6s_11_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mul_9ns_3ns_12_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mul_9s_9s_18_1_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mul_18ns_41ns_59_2_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mul_mul_5ns_11s_11_4_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mul_mul_12s_6s_16_4_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_mul_mul_15ns_12ns_26_4_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat_sdiv_8s_3s_8_12_seq_1.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ed4c/hdl/verilog/im2col_mat.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_im2col_mat_0_0/sim/design_1_im2col_mat_0_0.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/4c18/hdl/verilog/relu_control_s_axi.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/4c18/hdl/verilog/relu_gmem_m_axi.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/4c18/hdl/verilog/relu.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_relu_0_0/sim/design_1_relu_0_0.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b8b3/hdl/verilog/quantization_control_s_axi.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b8b3/hdl/verilog/quantization_gmem_m_axi.v" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b8b3/hdl/verilog/quantization.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_quantization_0_0/sim/design_1_quantization_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/e1e6/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/8ae1/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_6 $vhdlan_opts \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/8ae1/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/8ae1/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_24 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/fa53/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ac57/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/8fe4/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps7_0_50M_0/sim/design_1_rst_ps7_0_50M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_1/sim/design_1_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_24 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/23c0/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/38b4/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_pool_0_0/drivers/pool_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_matmul_0_0/drivers/matmul_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_mat_add_0_0/drivers/mat_add_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_im2col_mat_0_0/drivers/im2col_mat_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_relu_0_0/drivers/relu_v1_0/src" +incdir+"$ref_dir/../../../../final1.gen/sources_1/bd/design_1/ip/design_1_quantization_0_0/drivers/quantization_v1_0/src" +incdir+"D:/vivado/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_0/sim/design_1_auto_us_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_1/sim/design_1_auto_us_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_2/sim/design_1_auto_us_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_3/sim/design_1_auto_us_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_4/sim/design_1_auto_us_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_5/sim/design_1_auto_us_5.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
