// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pool_pool,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=2283,HLS_SYN_LUT=2583,HLS_VERSION=2021_2}" *)

module pool (
        ap_local_block,
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 49'd1;
parameter    ap_ST_fsm_state2 = 49'd2;
parameter    ap_ST_fsm_state3 = 49'd4;
parameter    ap_ST_fsm_state4 = 49'd8;
parameter    ap_ST_fsm_state5 = 49'd16;
parameter    ap_ST_fsm_state6 = 49'd32;
parameter    ap_ST_fsm_state7 = 49'd64;
parameter    ap_ST_fsm_state8 = 49'd128;
parameter    ap_ST_fsm_state9 = 49'd256;
parameter    ap_ST_fsm_state10 = 49'd512;
parameter    ap_ST_fsm_state11 = 49'd1024;
parameter    ap_ST_fsm_state12 = 49'd2048;
parameter    ap_ST_fsm_state13 = 49'd4096;
parameter    ap_ST_fsm_state14 = 49'd8192;
parameter    ap_ST_fsm_state15 = 49'd16384;
parameter    ap_ST_fsm_state16 = 49'd32768;
parameter    ap_ST_fsm_state17 = 49'd65536;
parameter    ap_ST_fsm_state18 = 49'd131072;
parameter    ap_ST_fsm_state19 = 49'd262144;
parameter    ap_ST_fsm_state20 = 49'd524288;
parameter    ap_ST_fsm_state21 = 49'd1048576;
parameter    ap_ST_fsm_state22 = 49'd2097152;
parameter    ap_ST_fsm_state23 = 49'd4194304;
parameter    ap_ST_fsm_state24 = 49'd8388608;
parameter    ap_ST_fsm_state25 = 49'd16777216;
parameter    ap_ST_fsm_state26 = 49'd33554432;
parameter    ap_ST_fsm_state27 = 49'd67108864;
parameter    ap_ST_fsm_state28 = 49'd134217728;
parameter    ap_ST_fsm_state29 = 49'd268435456;
parameter    ap_ST_fsm_state30 = 49'd536870912;
parameter    ap_ST_fsm_state31 = 49'd1073741824;
parameter    ap_ST_fsm_state32 = 49'd2147483648;
parameter    ap_ST_fsm_state33 = 49'd4294967296;
parameter    ap_ST_fsm_state34 = 49'd8589934592;
parameter    ap_ST_fsm_state35 = 49'd17179869184;
parameter    ap_ST_fsm_state36 = 49'd34359738368;
parameter    ap_ST_fsm_state37 = 49'd68719476736;
parameter    ap_ST_fsm_state38 = 49'd137438953472;
parameter    ap_ST_fsm_state39 = 49'd274877906944;
parameter    ap_ST_fsm_state40 = 49'd549755813888;
parameter    ap_ST_fsm_state41 = 49'd1099511627776;
parameter    ap_ST_fsm_state42 = 49'd2199023255552;
parameter    ap_ST_fsm_state43 = 49'd4398046511104;
parameter    ap_ST_fsm_state44 = 49'd8796093022208;
parameter    ap_ST_fsm_state45 = 49'd17592186044416;
parameter    ap_ST_fsm_state46 = 49'd35184372088832;
parameter    ap_ST_fsm_state47 = 49'd70368744177664;
parameter    ap_ST_fsm_state48 = 49'd140737488355328;
parameter    ap_ST_fsm_state49 = 49'd281474976710656;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

output   ap_local_block;
input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

wire   [0:0] ap_local_deadlock;
 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [48:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] mat_in;
wire   [63:0] mat_out;
wire   [5:0] inchannels;
wire   [5:0] mat_h;
wire   [5:0] mat_w;
wire  signed [7:0] kh;
wire  signed [7:0] kw;
wire   [1:0] mode;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state18;
reg   [0:0] first_itr_reg_205;
reg    gmem_blk_n_W;
wire    ap_CS_fsm_state44;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state49;
reg   [0:0] icmp_ln1072_2_reg_850;
reg   [1:0] mode_read_reg_632;
reg   [7:0] kw_read_reg_639;
reg  signed [7:0] kh_read_reg_648;
reg   [5:0] mat_w_read_reg_655;
reg  signed [5:0] mat_h_read_reg_662;
reg   [5:0] inchannels_read_reg_667;
reg   [63:0] mat_out_read_reg_672;
reg   [63:0] mat_in_read_reg_677;
wire   [5:0] trunc_ln885_fu_300_p1;
reg   [5:0] trunc_ln885_reg_698;
wire   [5:0] trunc_ln885_1_fu_304_p1;
reg   [5:0] trunc_ln885_1_reg_703;
wire   [5:0] grp_fu_284_p2;
reg   [5:0] sdiv_ln1558_reg_708;
wire    ap_CS_fsm_state11;
wire   [5:0] grp_fu_294_p2;
reg   [5:0] sdiv_ln1558_1_reg_713;
wire  signed [10:0] num_w_cast_fu_332_p1;
reg  signed [10:0] num_w_cast_reg_718;
wire    ap_CS_fsm_state12;
wire  signed [11:0] mul_i844_fu_336_p2;
reg  signed [11:0] mul_i844_reg_723;
wire  signed [31:0] conv3_i829_fu_342_p1;
reg   [31:0] conv3_i829_reg_729;
wire  signed [9:0] mul_i_i_cast_fu_353_p1;
reg  signed [9:0] mul_i_i_cast_reg_734;
wire  signed [9:0] mat_w_cast3_fu_357_p1;
reg  signed [9:0] mat_w_cast3_reg_739;
wire   [0:0] cmp_i_i793_fu_360_p2;
reg   [0:0] cmp_i_i793_reg_744;
wire  signed [10:0] mat_w_cast_fu_365_p1;
reg  signed [10:0] mat_w_cast_reg_749;
wire  signed [15:0] sext_ln28_1_fu_368_p1;
reg  signed [15:0] sext_ln28_1_reg_754;
wire   [0:0] cmp_i_i_fu_371_p2;
reg   [0:0] cmp_i_i_reg_759;
wire  signed [15:0] num_h_cast_fu_388_p1;
reg  signed [15:0] num_h_cast_reg_763;
wire   [0:0] cmp_i8301296_fu_392_p2;
reg   [0:0] cmp_i8301296_reg_768;
wire  signed [18:0] sext_ln1558_2_fu_398_p1;
reg  signed [18:0] sext_ln1558_2_reg_772;
wire   [15:0] bound_fu_408_p2;
reg   [15:0] bound_reg_777;
wire   [10:0] add_ln1072_fu_420_p2;
reg   [10:0] add_ln1072_reg_782;
wire    ap_CS_fsm_state13;
wire   [4:0] m_V_2_fu_434_p2;
reg   [4:0] m_V_2_reg_790;
wire   [0:0] icmp_ln1072_fu_429_p2;
wire  signed [15:0] grp_fu_613_p2;
reg   [15:0] mul_ln28_reg_805;
wire    ap_CS_fsm_state16;
reg   [63:0] gmem_addr_reg_810;
wire  signed [5:0] i_V_1_fu_502_p2;
reg  signed [5:0] i_V_1_reg_819;
wire    ap_CS_fsm_state17;
wire   [5:0] addr_V_6_fu_562_p3;
reg   [5:0] addr_V_6_reg_825;
wire   [5:0] addr_V_7_fu_570_p3;
reg   [5:0] addr_V_7_reg_831;
wire    ap_CS_fsm_state21;
wire   [17:0] trunc_ln229_fu_590_p1;
wire    ap_CS_fsm_state43;
wire   [0:0] icmp_ln1072_2_fu_597_p2;
wire    grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_start;
wire    grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_done;
wire    grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_idle;
wire    grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_ready;
wire    grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWVALID;
wire   [63:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWADDR;
wire   [0:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWID;
wire   [31:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWLEN;
wire   [2:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWSIZE;
wire   [1:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWBURST;
wire   [1:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWLOCK;
wire   [3:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWCACHE;
wire   [2:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWPROT;
wire   [3:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWQOS;
wire   [3:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWREGION;
wire   [0:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWUSER;
wire    grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_WVALID;
wire   [31:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_WDATA;
wire   [3:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_WSTRB;
wire    grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_WLAST;
wire   [0:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_WID;
wire   [0:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_WUSER;
wire    grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARVALID;
wire   [63:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARADDR;
wire   [0:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARID;
wire   [31:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARLEN;
wire   [2:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARSIZE;
wire   [1:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARBURST;
wire   [1:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARLOCK;
wire   [3:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARCACHE;
wire   [2:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARPROT;
wire   [3:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARQOS;
wire   [3:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARREGION;
wire   [0:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARUSER;
wire    grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_RREADY;
wire    grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_BREADY;
wire   [17:0] grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_p_out;
wire    grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_p_out_ap_vld;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
wire   [31:0] gmem_WDATA;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [8:0] gmem_RFIFONUM;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
reg    gmem_BREADY;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
reg    ap_block_state49;
reg  signed [5:0] i_V_reg_219;
reg   [5:0] addr_V_1_reg_231;
reg  signed [5:0] addr_V_8_reg_243;
reg   [17:0] p_lcssa2_lcssa6_reg_255;
reg    grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_start_reg;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire  signed [63:0] sext_ln28_fu_483_p1;
reg    ap_block_state18_io;
reg  signed [10:0] phi_mul_fu_130;
wire   [0:0] icmp_ln1072_1_fu_497_p2;
reg   [4:0] m_V_fu_134;
wire  signed [5:0] sext_ln1558_fu_280_p0;
wire  signed [6:0] grp_fu_284_p0;
wire  signed [5:0] sext_ln1558_1_fu_290_p0;
wire  signed [6:0] grp_fu_294_p0;
wire  signed [7:0] trunc_ln885_fu_300_p0;
wire  signed [7:0] trunc_ln885_1_fu_304_p0;
wire  signed [5:0] num_h_fu_318_p1;
wire  signed [5:0] num_w_fu_321_p1;
wire   [8:0] rhs_fu_346_p3;
wire   [15:0] mul_i86_fu_382_p2;
wire   [7:0] bound_fu_408_p0;
wire   [7:0] bound_fu_408_p1;
wire  signed [10:0] add_ln1072_fu_420_p0;
wire   [5:0] zext_ln1072_fu_425_p1;
wire   [4:0] empty_24_fu_444_p0;
wire  signed [5:0] empty_24_fu_444_p1;
wire  signed [10:0] empty_24_fu_444_p2;
wire  signed [15:0] grp_fu_607_p2;
wire   [17:0] tmp_fu_457_p3;
wire  signed [63:0] p_cast14_fu_464_p1;
wire   [63:0] empty_26_fu_468_p2;
wire   [61:0] trunc_ln1_fu_473_p4;
wire  signed [11:0] sext_ln1072_fu_493_p1;
wire  signed [9:0] sext_ln1540_fu_522_p1;
wire   [9:0] ret_fu_526_p2;
wire   [0:0] icmp_ln1080_fu_531_p2;
wire   [5:0] addr_V_3_fu_541_p2;
wire   [5:0] addr_V_fu_536_p2;
wire   [0:0] icmp_ln1068_fu_516_p2;
wire   [5:0] addr_V_5_fu_546_p3;
wire   [5:0] addr_V_4_fu_554_p3;
wire   [18:0] grp_fu_585_p0;
wire  signed [15:0] grp_fu_585_p1;
wire   [17:0] grp_fu_585_p2;
wire  signed [11:0] sext_ln1072_4_fu_594_p1;
wire  signed [5:0] grp_fu_607_p1;
wire  signed [5:0] grp_fu_613_p1;
reg    grp_fu_284_ap_start;
wire    grp_fu_284_ap_done;
reg    grp_fu_294_ap_start;
wire    grp_fu_294_ap_done;
reg    grp_fu_585_ap_start;
wire    grp_fu_585_ap_done;
reg   [48:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
reg    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
reg    ap_ST_fsm_state49_blk;
wire   [15:0] bound_fu_408_p00;
wire   [15:0] bound_fu_408_p10;
wire   [10:0] empty_24_fu_444_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 49'd1;
#0 grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_start_reg = 1'b0;
end

pool_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4 grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_start),
    .ap_done(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_done),
    .ap_idle(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_idle),
    .ap_ready(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_ready),
    .m_axi_gmem_AWVALID(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(gmem_RLAST),
    .m_axi_gmem_RID(gmem_RID),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(gmem_RUSER),
    .m_axi_gmem_RRESP(gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln39(cmp_i_i793_reg_744),
    .kw(kw_read_reg_639),
    .bound(bound_reg_777),
    .conv_i_i722(addr_V_7_reg_831),
    .conv_i8_i707(mat_w_read_reg_655),
    .mul_i749(mul_ln28_reg_805),
    .sext_ln44(addr_V_6_reg_825),
    .mode(mode_read_reg_632),
    .mat_in(mat_in_read_reg_677),
    .p_out(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_p_out),
    .p_out_ap_vld(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_p_out_ap_vld)
);

pool_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .mat_in(mat_in),
    .mat_out(mat_out),
    .inchannels(inchannels),
    .mat_h(mat_h),
    .mat_w(mat_w),
    .kh(kh),
    .kw(kw),
    .mode(mode),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_local_deadlock(ap_local_deadlock)
);

pool_gmem_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARADDR),
    .I_ARID(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARID),
    .I_ARLEN(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARLEN),
    .I_ARSIZE(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARSIZE),
    .I_ARLOCK(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARLOCK),
    .I_ARCACHE(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARCACHE),
    .I_ARQOS(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARQOS),
    .I_ARPROT(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARPROT),
    .I_ARUSER(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARUSER),
    .I_ARBURST(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARBURST),
    .I_ARREGION(grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARREGION),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_addr_reg_810),
    .I_AWID(1'd0),
    .I_AWLEN(conv3_i829_reg_729),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(gmem_WDATA),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

pool_sdiv_7s_8s_6_11_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 11 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 6 ))
sdiv_7s_8s_6_11_seq_1_U14(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_284_ap_start),
    .done(grp_fu_284_ap_done),
    .din0(grp_fu_284_p0),
    .din1(kh),
    .ce(1'b1),
    .dout(grp_fu_284_p2)
);

pool_sdiv_7s_8s_6_11_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 11 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 6 ))
sdiv_7s_8s_6_11_seq_1_U15(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_294_ap_start),
    .done(grp_fu_294_ap_done),
    .din0(grp_fu_294_p0),
    .din1(kw),
    .ce(1'b1),
    .dout(grp_fu_294_p2)
);

pool_mul_6s_6s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mul_6s_6s_12_1_1_U16(
    .din0(num_w_fu_321_p1),
    .din1(num_h_fu_318_p1),
    .dout(mul_i844_fu_336_p2)
);

pool_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U17(
    .din0(kw_read_reg_639),
    .din1(kh_read_reg_648),
    .dout(mul_i86_fu_382_p2)
);

pool_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U18(
    .din0(bound_fu_408_p0),
    .din1(bound_fu_408_p1),
    .dout(bound_fu_408_p2)
);

pool_mul_5ns_6s_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_5ns_6s_11_1_1_U19(
    .din0(empty_24_fu_444_p0),
    .din1(empty_24_fu_444_p1),
    .dout(empty_24_fu_444_p2)
);

pool_sdiv_19ns_16s_18_23_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 23 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 18 ))
sdiv_19ns_16s_18_23_seq_1_U20(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_585_ap_start),
    .done(grp_fu_585_ap_done),
    .din0(grp_fu_585_p0),
    .din1(grp_fu_585_p1),
    .ce(1'b1),
    .dout(grp_fu_585_p2)
);

pool_mul_mul_11s_6s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_mul_11s_6s_16_4_1_U21(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(empty_24_fu_444_p2),
    .din1(grp_fu_607_p1),
    .ce(1'b1),
    .dout(grp_fu_607_p2)
);

pool_mul_mul_11s_6s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_mul_11s_6s_16_4_1_U22(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(phi_mul_fu_130),
    .din1(grp_fu_613_p1),
    .ce(1'b1),
    .dout(grp_fu_613_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_start_reg <= 1'b1;
        end else if ((grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_ready == 1'b1)) begin
            grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (cmp_i8301296_reg_768 == 1'd1))) begin
        addr_V_1_reg_231 <= 6'd0;
    end else if ((~((gmem_BVALID == 1'b0) & (icmp_ln1072_2_reg_850 == 1'd0)) & (1'b1 == ap_CS_fsm_state49))) begin
        addr_V_1_reg_231 <= addr_V_7_reg_831;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (cmp_i8301296_reg_768 == 1'd1))) begin
        addr_V_8_reg_243 <= 6'd0;
    end else if ((~((gmem_BVALID == 1'b0) & (icmp_ln1072_2_reg_850 == 1'd0)) & (1'b1 == ap_CS_fsm_state49))) begin
        addr_V_8_reg_243 <= addr_V_6_reg_825;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (cmp_i8301296_reg_768 == 1'd1))) begin
        first_itr_reg_205 <= 1'd1;
    end else if ((~((gmem_BVALID == 1'b0) & (icmp_ln1072_2_reg_850 == 1'd0)) & (1'b1 == ap_CS_fsm_state49))) begin
        first_itr_reg_205 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (cmp_i8301296_reg_768 == 1'd1))) begin
        i_V_reg_219 <= 6'd0;
    end else if ((~((gmem_BVALID == 1'b0) & (icmp_ln1072_2_reg_850 == 1'd0)) & (1'b1 == ap_CS_fsm_state49))) begin
        i_V_reg_219 <= i_V_1_reg_819;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        m_V_fu_134 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state17) & ((icmp_ln1072_1_fu_497_p2 == 1'd0) | (cmp_i8301296_reg_768 == 1'd0)))) begin
        m_V_fu_134 <= m_V_2_reg_790;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) & (cmp_i_i_reg_759 == 1'd0))) begin
        p_lcssa2_lcssa6_reg_255 <= grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_p_out;
    end else if (((1'b1 == ap_CS_fsm_state43) & (cmp_i_i_reg_759 == 1'd1))) begin
        p_lcssa2_lcssa6_reg_255 <= trunc_ln229_fu_590_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_mul_fu_130 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state17) & ((icmp_ln1072_1_fu_497_p2 == 1'd0) | (cmp_i8301296_reg_768 == 1'd0)))) begin
        phi_mul_fu_130 <= add_ln1072_reg_782;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        add_ln1072_reg_782 <= add_ln1072_fu_420_p2;
        m_V_2_reg_790 <= m_V_2_fu_434_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        addr_V_6_reg_825 <= addr_V_6_fu_562_p3;
        addr_V_7_reg_831 <= addr_V_7_fu_570_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        bound_reg_777 <= bound_fu_408_p2;
        cmp_i8301296_reg_768 <= cmp_i8301296_fu_392_p2;
        cmp_i_i793_reg_744 <= cmp_i_i793_fu_360_p2;
        cmp_i_i_reg_759 <= cmp_i_i_fu_371_p2;
        conv3_i829_reg_729 <= conv3_i829_fu_342_p1;
        mat_w_cast3_reg_739 <= mat_w_cast3_fu_357_p1;
        mat_w_cast_reg_749 <= mat_w_cast_fu_365_p1;
        mul_i844_reg_723 <= mul_i844_fu_336_p2;
        mul_i_i_cast_reg_734[9 : 1] <= mul_i_i_cast_fu_353_p1[9 : 1];
        num_h_cast_reg_763 <= num_h_cast_fu_388_p1;
        num_w_cast_reg_718 <= num_w_cast_fu_332_p1;
        sext_ln1558_2_reg_772 <= sext_ln1558_2_fu_398_p1;
        sext_ln28_1_reg_754 <= sext_ln28_1_fu_368_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (cmp_i8301296_reg_768 == 1'd1))) begin
        gmem_addr_reg_810 <= sext_ln28_fu_483_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (cmp_i8301296_reg_768 == 1'd1))) begin
        i_V_1_reg_819 <= i_V_1_fu_502_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        icmp_ln1072_2_reg_850 <= icmp_ln1072_2_fu_597_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        inchannels_read_reg_667 <= inchannels;
        kh_read_reg_648 <= kh;
        kw_read_reg_639 <= kw;
        mat_h_read_reg_662 <= mat_h;
        mat_in_read_reg_677 <= mat_in;
        mat_out_read_reg_672 <= mat_out;
        mat_w_read_reg_655 <= mat_w;
        mode_read_reg_632 <= mode;
        trunc_ln885_1_reg_703 <= trunc_ln885_1_fu_304_p1;
        trunc_ln885_reg_698 <= trunc_ln885_fu_300_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        mul_ln28_reg_805 <= grp_fu_613_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        sdiv_ln1558_1_reg_713 <= grp_fu_294_p2;
        sdiv_ln1558_reg_708 <= grp_fu_284_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state18_io)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

always @ (*) begin
    if ((gmem_WREADY == 1'b0)) begin
        ap_ST_fsm_state44_blk = 1'b1;
    end else begin
        ap_ST_fsm_state44_blk = 1'b0;
    end
end

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

always @ (*) begin
    if (((gmem_BVALID == 1'b0) & (icmp_ln1072_2_reg_850 == 1'd0))) begin
        ap_ST_fsm_state49_blk = 1'b1;
    end else begin
        ap_ST_fsm_state49_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln1072_fu_429_p2 == 1'd0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln1072_fu_429_p2 == 1'd0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19))) begin
        gmem_ARVALID = grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) & (1'b0 == ap_block_state18_io) & (first_itr_reg_205 == 1'd1))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((gmem_BVALID == 1'b0) & (icmp_ln1072_2_reg_850 == 1'd0)) & (1'b1 == ap_CS_fsm_state49) & (icmp_ln1072_2_reg_850 == 1'd0))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19))) begin
        gmem_RREADY = grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state44) & (gmem_WREADY == 1'b1))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) & (first_itr_reg_205 == 1'd1))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) & (icmp_ln1072_2_reg_850 == 1'd0))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        grp_fu_284_ap_start = 1'b1;
    end else begin
        grp_fu_284_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        grp_fu_294_ap_start = 1'b1;
    end else begin
        grp_fu_294_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (cmp_i_i_reg_759 == 1'd1))) begin
        grp_fu_585_ap_start = 1'b1;
    end else begin
        grp_fu_585_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln1072_fu_429_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((1'b1 == ap_CS_fsm_state17) & ((icmp_ln1072_1_fu_497_p2 == 1'd0) | (cmp_i8301296_reg_768 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((1'b1 == ap_CS_fsm_state18) & (1'b0 == ap_block_state18_io))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((1'b1 == ap_CS_fsm_state20) & (grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((1'b1 == ap_CS_fsm_state21) & (cmp_i_i_reg_759 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            if (((1'b1 == ap_CS_fsm_state44) & (gmem_WREADY == 1'b1) & (icmp_ln1072_2_reg_850 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state49;
            end else if (((1'b1 == ap_CS_fsm_state44) & (gmem_WREADY == 1'b1) & (icmp_ln1072_2_reg_850 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            if ((~((gmem_BVALID == 1'b0) & (icmp_ln1072_2_reg_850 == 1'd0)) & (1'b1 == ap_CS_fsm_state49))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state49;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1072_fu_420_p0 = phi_mul_fu_130;

assign add_ln1072_fu_420_p2 = ($signed(add_ln1072_fu_420_p0) + $signed(mat_w_cast_reg_749));

assign addr_V_3_fu_541_p2 = ($signed(addr_V_8_reg_243) + $signed(trunc_ln885_1_reg_703));

assign addr_V_4_fu_554_p3 = ((icmp_ln1080_fu_531_p2[0:0] == 1'b1) ? addr_V_fu_536_p2 : addr_V_1_reg_231);

assign addr_V_5_fu_546_p3 = ((icmp_ln1080_fu_531_p2[0:0] == 1'b1) ? 6'd0 : addr_V_3_fu_541_p2);

assign addr_V_6_fu_562_p3 = ((icmp_ln1068_fu_516_p2[0:0] == 1'b1) ? addr_V_8_reg_243 : addr_V_5_fu_546_p3);

assign addr_V_7_fu_570_p3 = ((icmp_ln1068_fu_516_p2[0:0] == 1'b1) ? addr_V_1_reg_231 : addr_V_4_fu_554_p3);

assign addr_V_fu_536_p2 = (addr_V_1_reg_231 + trunc_ln885_reg_698);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

always @ (*) begin
    ap_block_state18_io = ((gmem_AWREADY == 1'b0) & (first_itr_reg_205 == 1'd1));
end

always @ (*) begin
    ap_block_state49 = ((gmem_BVALID == 1'b0) & (icmp_ln1072_2_reg_850 == 1'd0));
end

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'd0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bound_fu_408_p0 = bound_fu_408_p00;

assign bound_fu_408_p00 = $unsigned(kh_read_reg_648);

assign bound_fu_408_p1 = bound_fu_408_p10;

assign bound_fu_408_p10 = kw_read_reg_639;

assign cmp_i8301296_fu_392_p2 = (($signed(mul_i844_fu_336_p2) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign cmp_i_i793_fu_360_p2 = ((mode_read_reg_632 == 2'd2) ? 1'b1 : 1'b0);

assign cmp_i_i_fu_371_p2 = ((mode_read_reg_632 == 2'd0) ? 1'b1 : 1'b0);

assign conv3_i829_fu_342_p1 = mul_i844_fu_336_p2;

assign empty_24_fu_444_p0 = empty_24_fu_444_p00;

assign empty_24_fu_444_p00 = m_V_fu_134;

assign empty_24_fu_444_p1 = num_w_cast_reg_718;

assign empty_26_fu_468_p2 = ($signed(p_cast14_fu_464_p1) + $signed(mat_out_read_reg_672));

assign gmem_WDATA = p_lcssa2_lcssa6_reg_255;

assign grp_fu_284_p0 = sext_ln1558_fu_280_p0;

assign grp_fu_294_p0 = sext_ln1558_1_fu_290_p0;

assign grp_fu_585_p0 = grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_p_out;

assign grp_fu_585_p1 = sext_ln1558_2_reg_772;

assign grp_fu_607_p1 = num_h_cast_reg_763;

assign grp_fu_613_p1 = sext_ln28_1_reg_754;

assign grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_start = grp_pool_Pipeline_VITIS_LOOP_44_3_VITIS_LOOP_47_4_fu_264_ap_start_reg;

assign i_V_1_fu_502_p2 = ($signed(i_V_reg_219) + $signed(6'd1));

assign icmp_ln1068_fu_516_p2 = ((i_V_reg_219 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln1072_1_fu_497_p2 = (($signed(sext_ln1072_fu_493_p1) < $signed(mul_i844_reg_723)) ? 1'b1 : 1'b0);

assign icmp_ln1072_2_fu_597_p2 = (($signed(sext_ln1072_4_fu_594_p1) < $signed(mul_i844_reg_723)) ? 1'b1 : 1'b0);

assign icmp_ln1072_fu_429_p2 = (($signed(zext_ln1072_fu_425_p1) < $signed(inchannels_read_reg_667)) ? 1'b1 : 1'b0);

assign icmp_ln1080_fu_531_p2 = (($signed(ret_fu_526_p2) > $signed(mat_w_cast3_reg_739)) ? 1'b1 : 1'b0);

assign m_V_2_fu_434_p2 = (m_V_fu_134 + 5'd1);

assign mat_w_cast3_fu_357_p1 = $signed(mat_w_read_reg_655);

assign mat_w_cast_fu_365_p1 = $signed(mat_w_read_reg_655);

assign mul_i_i_cast_fu_353_p1 = $signed(rhs_fu_346_p3);

assign num_h_cast_fu_388_p1 = num_h_fu_318_p1;

assign num_h_fu_318_p1 = sdiv_ln1558_reg_708[5:0];

assign num_w_cast_fu_332_p1 = num_w_fu_321_p1;

assign num_w_fu_321_p1 = sdiv_ln1558_1_reg_713[5:0];

assign p_cast14_fu_464_p1 = $signed(tmp_fu_457_p3);

assign ret_fu_526_p2 = ($signed(mul_i_i_cast_reg_734) + $signed(sext_ln1540_fu_522_p1));

assign rhs_fu_346_p3 = {{kw_read_reg_639}, {1'd0}};

assign sext_ln1072_4_fu_594_p1 = i_V_1_reg_819;

assign sext_ln1072_fu_493_p1 = i_V_reg_219;

assign sext_ln1540_fu_522_p1 = addr_V_8_reg_243;

assign sext_ln1558_1_fu_290_p0 = mat_w;

assign sext_ln1558_2_fu_398_p1 = $signed(mul_i86_fu_382_p2);

assign sext_ln1558_fu_280_p0 = mat_h;

assign sext_ln28_1_fu_368_p1 = mat_h_read_reg_662;

assign sext_ln28_fu_483_p1 = $signed(trunc_ln1_fu_473_p4);

assign tmp_fu_457_p3 = {{grp_fu_607_p2}, {2'd0}};

assign trunc_ln1_fu_473_p4 = {{empty_26_fu_468_p2[63:2]}};

assign trunc_ln229_fu_590_p1 = grp_fu_585_p2[17:0];

assign trunc_ln885_1_fu_304_p0 = kw;

assign trunc_ln885_1_fu_304_p1 = trunc_ln885_1_fu_304_p0[5:0];

assign trunc_ln885_fu_300_p0 = kh;

assign trunc_ln885_fu_300_p1 = trunc_ln885_fu_300_p0[5:0];

assign zext_ln1072_fu_425_p1 = m_V_fu_134;

always @ (posedge ap_clk) begin
    mul_i_i_cast_reg_734[0] <= 1'b0;
end

endmodule //pool
