// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="im2col_mat_im2col_mat,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=3228,HLS_SYN_LUT=3521,HLS_VERSION=2021_2}" *)

module im2col_mat (
        ap_local_block,
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 31'd1;
parameter    ap_ST_fsm_state2 = 31'd2;
parameter    ap_ST_fsm_state3 = 31'd4;
parameter    ap_ST_fsm_state4 = 31'd8;
parameter    ap_ST_fsm_state5 = 31'd16;
parameter    ap_ST_fsm_state6 = 31'd32;
parameter    ap_ST_fsm_state7 = 31'd64;
parameter    ap_ST_fsm_state8 = 31'd128;
parameter    ap_ST_fsm_state9 = 31'd256;
parameter    ap_ST_fsm_state10 = 31'd512;
parameter    ap_ST_fsm_state11 = 31'd1024;
parameter    ap_ST_fsm_state12 = 31'd2048;
parameter    ap_ST_fsm_state13 = 31'd4096;
parameter    ap_ST_fsm_state14 = 31'd8192;
parameter    ap_ST_fsm_state15 = 31'd16384;
parameter    ap_ST_fsm_state16 = 31'd32768;
parameter    ap_ST_fsm_state17 = 31'd65536;
parameter    ap_ST_fsm_state18 = 31'd131072;
parameter    ap_ST_fsm_state19 = 31'd262144;
parameter    ap_ST_fsm_state20 = 31'd524288;
parameter    ap_ST_fsm_state21 = 31'd1048576;
parameter    ap_ST_fsm_state22 = 31'd2097152;
parameter    ap_ST_fsm_state23 = 31'd4194304;
parameter    ap_ST_fsm_state24 = 31'd8388608;
parameter    ap_ST_fsm_state25 = 31'd16777216;
parameter    ap_ST_fsm_state26 = 31'd33554432;
parameter    ap_ST_fsm_state27 = 31'd67108864;
parameter    ap_ST_fsm_state28 = 31'd134217728;
parameter    ap_ST_fsm_state29 = 31'd268435456;
parameter    ap_ST_fsm_state30 = 31'd536870912;
parameter    ap_ST_fsm_state31 = 31'd1073741824;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

output   ap_local_block;
input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

wire   [0:0] ap_local_deadlock;
 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [30:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] mat_in;
wire   [63:0] mat_out;
wire  signed [5:0] inchannels;
wire   [2:0] stride;
wire   [0:0] padding;
wire   [2:0] kernel_size;
wire  signed [5:0] mat_h;
wire  signed [5:0] mat_w;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state6;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_state13;
reg   [5:0] mat_w_read_reg_489;
reg  signed [5:0] mat_h_read_reg_496;
reg   [2:0] kernel_size_read_reg_501;
reg   [2:0] stride_read_reg_515;
reg  signed [5:0] inchannels_read_reg_522;
reg   [63:0] mat_out_read_reg_528;
reg   [63:0] mat_in_read_reg_533;
wire   [10:0] trunc_ln55_fu_215_p1;
reg   [10:0] trunc_ln55_reg_538;
wire   [1:0] trunc_ln37_fu_227_p1;
reg   [1:0] trunc_ln37_reg_553;
wire  signed [6:0] sext_ln18_1_fu_236_p1;
reg  signed [6:0] sext_ln18_1_reg_558;
wire    ap_CS_fsm_state4;
wire  signed [15:0] grp_fu_476_p2;
reg  signed [15:0] mul_ln37_reg_563;
wire   [63:0] zext_ln1072_fu_242_p1;
reg   [63:0] zext_ln1072_reg_568;
wire    ap_CS_fsm_state5;
reg   [63:0] gmem_addr_reg_576;
wire   [0:0] icmp_ln1072_fu_250_p2;
wire   [1:0] add_ln37_1_fu_290_p2;
reg   [1:0] add_ln37_1_reg_582;
wire  signed [7:0] sext_ln1558_fu_316_p1;
reg   [31:0] gmem_addr_read_reg_603;
wire   [7:0] trunc_ln37_2_fu_356_p1;
reg   [7:0] trunc_ln37_2_reg_608;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state24;
wire   [34:0] grp_fu_370_p2;
reg   [34:0] mul_ln18_reg_623;
wire    ap_CS_fsm_state25;
wire   [7:0] grp_fu_319_p2;
reg   [7:0] sdiv_ln1558_reg_630;
wire    ap_CS_fsm_state26;
wire   [7:0] grp_fu_334_p2;
reg   [7:0] sdiv_ln1558_1_reg_635;
wire   [17:0] mul50_fu_414_p2;
reg   [17:0] mul50_reg_650;
wire    ap_CS_fsm_state27;
wire   [40:0] grp_fu_382_p2;
reg   [40:0] mul_ln18_1_reg_655;
wire   [8:0] mul_ln43_fu_426_p2;
reg   [8:0] mul_ln43_reg_661;
wire    ap_CS_fsm_state28;
wire   [11:0] mul_ln43_1_fu_450_p2;
reg   [11:0] mul_ln43_1_reg_676;
wire    ap_CS_fsm_state29;
wire   [5:0] mul_ln43_2_fu_459_p2;
reg   [5:0] mul_ln43_2_reg_681;
wire   [58:0] grp_fu_438_p2;
reg   [58:0] mul_ln18_2_reg_686;
wire   [0:0] exitcond_flatten_mid1138_fu_465_p2;
reg   [0:0] exitcond_flatten_mid1138_reg_691;
wire   [0:0] icmp_ln1072_1_fu_470_p2;
reg   [0:0] icmp_ln1072_1_reg_696;
wire    ap_CS_fsm_state30;
reg   [10:0] mat_in_pad_V_address0;
reg    mat_in_pad_V_ce0;
reg    mat_in_pad_V_we0;
wire   [7:0] mat_in_pad_V_q0;
wire    grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_start;
wire    grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_done;
wire    grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_idle;
wire    grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_ready;
wire    grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWVALID;
wire   [63:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWADDR;
wire   [0:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWID;
wire   [31:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWLEN;
wire   [2:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWSIZE;
wire   [1:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWBURST;
wire   [1:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWLOCK;
wire   [3:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWCACHE;
wire   [2:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWPROT;
wire   [3:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWQOS;
wire   [3:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWREGION;
wire   [0:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWUSER;
wire    grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WVALID;
wire   [31:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WDATA;
wire   [3:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WSTRB;
wire    grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WLAST;
wire   [0:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WID;
wire   [0:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WUSER;
wire    grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARVALID;
wire   [63:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARADDR;
wire   [0:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARID;
wire   [31:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARLEN;
wire   [2:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARSIZE;
wire   [1:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARBURST;
wire   [1:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARLOCK;
wire   [3:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARCACHE;
wire   [2:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARPROT;
wire   [3:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARQOS;
wire   [3:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARREGION;
wire   [0:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARUSER;
wire    grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_RREADY;
wire    grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_BREADY;
wire   [10:0] grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_mat_in_pad_V_address0;
wire    grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_mat_in_pad_V_ce0;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [8:0] gmem_RFIFONUM;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
reg    gmem_BREADY;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
reg    grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_start_reg;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state15;
wire  signed [63:0] sext_ln37_fu_280_p1;
reg   [10:0] i_fu_104;
wire   [10:0] add_ln35_fu_255_p2;
wire  signed [11:0] mul33_fu_209_p2;
wire   [15:0] zext_ln1072_1_fu_246_p1;
wire   [63:0] add_ln37_fu_265_p2;
wire   [61:0] trunc_ln37_3_fu_270_p4;
wire   [1:0] trunc_ln37_1_fu_261_p1;
wire  signed [6:0] sext_ln1541_fu_300_p1;
wire  signed [6:0] sext_ln1558_1_fu_303_p1;
wire   [6:0] sub_ln1558_fu_306_p2;
wire  signed [7:0] grp_fu_319_p0;
wire  signed [2:0] grp_fu_319_p1;
wire   [6:0] sub_ln1558_1_fu_325_p2;
wire  signed [7:0] grp_fu_334_p0;
wire  signed [2:0] grp_fu_334_p1;
wire   [4:0] shl_ln_fu_340_p3;
wire   [31:0] zext_ln37_fu_347_p1;
wire   [31:0] lshr_ln37_fu_351_p2;
wire  signed [31:0] sext_ln18_3_fu_363_p1;
wire   [2:0] grp_fu_370_p0;
wire   [31:0] grp_fu_370_p1;
wire   [5:0] grp_fu_382_p0;
wire   [34:0] grp_fu_382_p1;
wire  signed [8:0] sext_ln40_fu_388_p1;
wire  signed [8:0] num_height_fu_391_p2;
wire  signed [8:0] sext_ln41_fu_401_p1;
wire  signed [8:0] num_width_fu_404_p2;
wire   [5:0] mul_ln43_fu_426_p0;
wire   [2:0] mul_ln43_fu_426_p1;
wire   [17:0] grp_fu_438_p0;
wire   [40:0] grp_fu_438_p1;
wire   [8:0] mul_ln43_1_fu_450_p0;
wire   [2:0] mul_ln43_1_fu_450_p1;
wire   [2:0] mul_ln43_2_fu_459_p0;
wire   [5:0] zext_ln43_4_fu_456_p1;
wire   [2:0] mul_ln43_2_fu_459_p1;
reg    grp_fu_319_ap_start;
wire    grp_fu_319_ap_done;
reg    grp_fu_334_ap_start;
wire    grp_fu_334_ap_done;
reg   [30:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
reg    ap_ST_fsm_state31_blk;
wire   [34:0] grp_fu_370_p00;
wire   [34:0] grp_fu_370_p10;
wire   [40:0] grp_fu_382_p00;
wire   [40:0] grp_fu_382_p10;
wire   [58:0] grp_fu_438_p00;
wire   [58:0] grp_fu_438_p10;
wire   [11:0] mul_ln43_1_fu_450_p00;
wire   [11:0] mul_ln43_1_fu_450_p10;
wire   [8:0] mul_ln43_fu_426_p00;
wire   [8:0] mul_ln43_fu_426_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 31'd1;
#0 grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_start_reg = 1'b0;
end

im2col_mat_mat_in_pad_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 2000 ),
    .AddressWidth( 11 ))
mat_in_pad_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mat_in_pad_V_address0),
    .ce0(mat_in_pad_V_ce0),
    .we0(mat_in_pad_V_we0),
    .d0(trunc_ln37_2_reg_608),
    .q0(mat_in_pad_V_q0)
);

im2col_mat_im2col_mat_Pipeline_VITIS_LOOP_56_7 grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_start),
    .ap_done(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_done),
    .ap_idle(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_idle),
    .ap_ready(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_ready),
    .m_axi_gmem_AWVALID(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(1'b0),
    .m_axi_gmem_ARADDR(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(1'b0),
    .m_axi_gmem_RREADY(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(32'd0),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(9'd0),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(gmem_BRESP),
    .m_axi_gmem_BID(gmem_BID),
    .m_axi_gmem_BUSER(gmem_BUSER),
    .zext_ln45(mul_ln43_1_reg_676),
    .rhs(stride_read_reg_515),
    .sext_ln1558_1(kernel_size_read_reg_501),
    .sext_ln18_1(mat_w_read_reg_489),
    .sext_ln885(stride_read_reg_515),
    .zext_ln43_5(mul_ln43_2_reg_681),
    .trunc_ln(trunc_ln55_reg_538),
    .zext_ln885(kernel_size_read_reg_501),
    .mul_ln18_2(mul_ln18_2_reg_686),
    .mat_in_pad_V_address0(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_mat_in_pad_V_address0),
    .mat_in_pad_V_ce0(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_mat_in_pad_V_ce0),
    .mat_in_pad_V_q0(mat_in_pad_V_q0),
    .conv_i_i208(kernel_size_read_reg_501),
    .mul_ln18_1(mul_ln18_1_reg_655),
    .icmp_ln1072_1(icmp_ln1072_1_reg_696),
    .mul_ln18(mul_ln18_reg_623),
    .exitcond_flatten_mid1138(exitcond_flatten_mid1138_reg_691),
    .sext_ln56(mat_w_read_reg_489),
    .mat_out(mat_out_read_reg_528)
);

im2col_mat_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .mat_in(mat_in),
    .mat_out(mat_out),
    .inchannels(inchannels),
    .stride(stride),
    .padding(padding),
    .kernel_size(kernel_size),
    .mat_h(mat_h),
    .mat_w(mat_w),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_local_deadlock(ap_local_deadlock)
);

im2col_mat_gmem_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_addr_reg_576),
    .I_ARID(1'd0),
    .I_ARLEN(32'd1),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWADDR),
    .I_AWID(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWID),
    .I_AWLEN(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWLEN),
    .I_AWSIZE(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWSIZE),
    .I_AWLOCK(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWLOCK),
    .I_AWCACHE(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWCACHE),
    .I_AWQOS(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWQOS),
    .I_AWPROT(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWPROT),
    .I_AWUSER(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWUSER),
    .I_AWBURST(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWBURST),
    .I_AWREGION(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWREGION),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WDATA),
    .I_WID(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WID),
    .I_WUSER(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WUSER),
    .I_WLAST(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WLAST),
    .I_WSTRB(grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

im2col_mat_mul_6s_6s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mul_6s_6s_12_1_1_U33(
    .din0(mat_w),
    .din1(mat_h),
    .dout(mul33_fu_209_p2)
);

im2col_mat_sdiv_8s_3s_8_12_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sdiv_8s_3s_8_12_seq_1_U34(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_319_ap_start),
    .done(grp_fu_319_ap_done),
    .din0(grp_fu_319_p0),
    .din1(grp_fu_319_p1),
    .ce(1'b1),
    .dout(grp_fu_319_p2)
);

im2col_mat_sdiv_8s_3s_8_12_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sdiv_8s_3s_8_12_seq_1_U35(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_334_ap_start),
    .done(grp_fu_334_ap_done),
    .din0(grp_fu_334_p0),
    .din1(grp_fu_334_p1),
    .ce(1'b1),
    .dout(grp_fu_334_p2)
);

im2col_mat_mul_3ns_32ns_35_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 35 ))
mul_3ns_32ns_35_2_1_U36(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_370_p0),
    .din1(grp_fu_370_p1),
    .ce(1'b1),
    .dout(grp_fu_370_p2)
);

im2col_mat_mul_6ns_35ns_41_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 35 ),
    .dout_WIDTH( 41 ))
mul_6ns_35ns_41_2_1_U37(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_382_p0),
    .din1(grp_fu_382_p1),
    .ce(1'b1),
    .dout(grp_fu_382_p2)
);

im2col_mat_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U38(
    .din0(num_width_fu_404_p2),
    .din1(num_height_fu_391_p2),
    .dout(mul50_fu_414_p2)
);

im2col_mat_mul_6ns_3ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 9 ))
mul_6ns_3ns_9_1_1_U39(
    .din0(mul_ln43_fu_426_p0),
    .din1(mul_ln43_fu_426_p1),
    .dout(mul_ln43_fu_426_p2)
);

im2col_mat_mul_18ns_41ns_59_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 41 ),
    .dout_WIDTH( 59 ))
mul_18ns_41ns_59_2_1_U40(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_438_p0),
    .din1(grp_fu_438_p1),
    .ce(1'b1),
    .dout(grp_fu_438_p2)
);

im2col_mat_mul_9ns_3ns_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 12 ))
mul_9ns_3ns_12_1_1_U41(
    .din0(mul_ln43_1_fu_450_p0),
    .din1(mul_ln43_1_fu_450_p1),
    .dout(mul_ln43_1_fu_450_p2)
);

im2col_mat_mul_3ns_3ns_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 6 ))
mul_3ns_3ns_6_1_1_U42(
    .din0(mul_ln43_2_fu_459_p0),
    .din1(mul_ln43_2_fu_459_p1),
    .dout(mul_ln43_2_fu_459_p2)
);

im2col_mat_mul_mul_12s_6s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_mul_12s_6s_16_4_1_U43(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(mul33_fu_209_p2),
    .din1(inchannels),
    .ce(1'b1),
    .dout(grp_fu_476_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state30)) begin
            grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_start_reg <= 1'b1;
        end else if ((grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_ready == 1'b1)) begin
            grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_104 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln1072_fu_250_p2 == 1'd0))) begin
        i_fu_104 <= add_ln35_fu_255_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln1072_fu_250_p2 == 1'd0))) begin
        add_ln37_1_reg_582 <= add_ln37_1_fu_290_p2;
        gmem_addr_reg_576 <= sext_ln37_fu_280_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        exitcond_flatten_mid1138_reg_691 <= exitcond_flatten_mid1138_fu_465_p2;
        mul_ln18_2_reg_686 <= grp_fu_438_p2;
        mul_ln43_1_reg_676 <= mul_ln43_1_fu_450_p2;
        mul_ln43_2_reg_681 <= mul_ln43_2_fu_459_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        gmem_addr_read_reg_603 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        icmp_ln1072_1_reg_696 <= icmp_ln1072_1_fu_470_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        inchannels_read_reg_522 <= inchannels;
        kernel_size_read_reg_501 <= kernel_size;
        mat_h_read_reg_496 <= mat_h;
        mat_in_read_reg_533 <= mat_in;
        mat_out_read_reg_528 <= mat_out;
        mat_w_read_reg_489 <= mat_w;
        stride_read_reg_515 <= stride;
        trunc_ln37_reg_553 <= trunc_ln37_fu_227_p1;
        trunc_ln55_reg_538 <= trunc_ln55_fu_215_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        mul50_reg_650 <= mul50_fu_414_p2;
        mul_ln18_1_reg_655 <= grp_fu_382_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        mul_ln18_reg_623 <= grp_fu_370_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mul_ln37_reg_563 <= grp_fu_476_p2;
        sext_ln18_1_reg_558 <= sext_ln18_1_fu_236_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        mul_ln43_reg_661 <= mul_ln43_fu_426_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        sdiv_ln1558_1_reg_635 <= grp_fu_334_p2;
        sdiv_ln1558_reg_630 <= grp_fu_319_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        trunc_ln37_2_reg_608 <= trunc_ln37_2_fu_356_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        zext_ln1072_reg_568[10 : 0] <= zext_ln1072_fu_242_p1[10 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

always @ (*) begin
    if ((grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_done == 1'b0)) begin
        ap_ST_fsm_state31_blk = 1'b1;
    end else begin
        ap_ST_fsm_state31_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) & (grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) & (grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (gmem_ARREADY == 1'b1))) begin
        gmem_ARVALID = 1'b1;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_AWVALID = grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_AWVALID;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_BREADY = grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_BREADY;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (gmem_RVALID == 1'b1))) begin
        gmem_RREADY = 1'b1;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_WVALID = grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_m_axi_gmem_WVALID;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln1072_fu_250_p2 == 1'd1))) begin
        grp_fu_319_ap_start = 1'b1;
    end else begin
        grp_fu_319_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln1072_fu_250_p2 == 1'd1))) begin
        grp_fu_334_ap_start = 1'b1;
    end else begin
        grp_fu_334_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        mat_in_pad_V_address0 = zext_ln1072_reg_568;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        mat_in_pad_V_address0 = grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_mat_in_pad_V_address0;
    end else begin
        mat_in_pad_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        mat_in_pad_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        mat_in_pad_V_ce0 = grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_mat_in_pad_V_ce0;
    end else begin
        mat_in_pad_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        mat_in_pad_V_we0 = 1'b1;
    end else begin
        mat_in_pad_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln1072_fu_250_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (gmem_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (gmem_RVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((1'b1 == ap_CS_fsm_state31) & (grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln35_fu_255_p2 = (i_fu_104 + 11'd1);

assign add_ln37_1_fu_290_p2 = (trunc_ln37_1_fu_261_p1 + trunc_ln37_reg_553);

assign add_ln37_fu_265_p2 = (zext_ln1072_fu_242_p1 + mat_in_read_reg_533);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'd0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign exitcond_flatten_mid1138_fu_465_p2 = ((mul_ln18_reg_623 == 35'd0) ? 1'b1 : 1'b0);

assign grp_fu_319_p0 = $signed(sub_ln1558_fu_306_p2);

assign grp_fu_319_p1 = sext_ln1558_fu_316_p1;

assign grp_fu_334_p0 = $signed(sub_ln1558_1_fu_325_p2);

assign grp_fu_334_p1 = sext_ln1558_fu_316_p1;

assign grp_fu_370_p0 = grp_fu_370_p00;

assign grp_fu_370_p00 = kernel_size_read_reg_501;

assign grp_fu_370_p1 = grp_fu_370_p10;

assign grp_fu_370_p10 = $unsigned(sext_ln18_3_fu_363_p1);

assign grp_fu_382_p0 = grp_fu_382_p00;

assign grp_fu_382_p00 = $unsigned(inchannels_read_reg_522);

assign grp_fu_382_p1 = grp_fu_382_p10;

assign grp_fu_382_p10 = mul_ln18_reg_623;

assign grp_fu_438_p0 = grp_fu_438_p00;

assign grp_fu_438_p00 = mul50_reg_650;

assign grp_fu_438_p1 = grp_fu_438_p10;

assign grp_fu_438_p10 = mul_ln18_1_reg_655;

assign grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_start = grp_im2col_mat_Pipeline_VITIS_LOOP_56_7_fu_178_ap_start_reg;

assign icmp_ln1072_1_fu_470_p2 = ((kernel_size_read_reg_501 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1072_fu_250_p2 = ((zext_ln1072_1_fu_246_p1 == mul_ln37_reg_563) ? 1'b1 : 1'b0);

assign lshr_ln37_fu_351_p2 = gmem_addr_read_reg_603 >> zext_ln37_fu_347_p1;

assign mul_ln43_1_fu_450_p0 = mul_ln43_1_fu_450_p00;

assign mul_ln43_1_fu_450_p00 = mul_ln43_reg_661;

assign mul_ln43_1_fu_450_p1 = mul_ln43_1_fu_450_p10;

assign mul_ln43_1_fu_450_p10 = kernel_size_read_reg_501;

assign mul_ln43_2_fu_459_p0 = zext_ln43_4_fu_456_p1;

assign mul_ln43_2_fu_459_p1 = zext_ln43_4_fu_456_p1;

assign mul_ln43_fu_426_p0 = mul_ln43_fu_426_p00;

assign mul_ln43_fu_426_p00 = $unsigned(inchannels_read_reg_522);

assign mul_ln43_fu_426_p1 = mul_ln43_fu_426_p10;

assign mul_ln43_fu_426_p10 = kernel_size_read_reg_501;

assign num_height_fu_391_p2 = ($signed(sext_ln40_fu_388_p1) + $signed(9'd1));

assign num_width_fu_404_p2 = ($signed(sext_ln41_fu_401_p1) + $signed(9'd1));

assign sext_ln1541_fu_300_p1 = mat_h_read_reg_496;

assign sext_ln1558_1_fu_303_p1 = $signed(kernel_size_read_reg_501);

assign sext_ln1558_fu_316_p1 = $signed(stride_read_reg_515);

assign sext_ln18_1_fu_236_p1 = $signed(mat_w_read_reg_489);

assign sext_ln18_3_fu_363_p1 = $signed(kernel_size_read_reg_501);

assign sext_ln37_fu_280_p1 = $signed(trunc_ln37_3_fu_270_p4);

assign sext_ln40_fu_388_p1 = $signed(sdiv_ln1558_reg_630);

assign sext_ln41_fu_401_p1 = $signed(sdiv_ln1558_1_reg_635);

assign shl_ln_fu_340_p3 = {{add_ln37_1_reg_582}, {3'd0}};

assign sub_ln1558_1_fu_325_p2 = ($signed(sext_ln18_1_reg_558) - $signed(sext_ln1558_1_fu_303_p1));

assign sub_ln1558_fu_306_p2 = ($signed(sext_ln1541_fu_300_p1) - $signed(sext_ln1558_1_fu_303_p1));

assign trunc_ln37_1_fu_261_p1 = i_fu_104[1:0];

assign trunc_ln37_2_fu_356_p1 = lshr_ln37_fu_351_p2[7:0];

assign trunc_ln37_3_fu_270_p4 = {{add_ln37_fu_265_p2[63:2]}};

assign trunc_ln37_fu_227_p1 = mat_in[1:0];

assign trunc_ln55_fu_215_p1 = mul33_fu_209_p2[10:0];

assign zext_ln1072_1_fu_246_p1 = i_fu_104;

assign zext_ln1072_fu_242_p1 = i_fu_104;

assign zext_ln37_fu_347_p1 = shl_ln_fu_340_p3;

assign zext_ln43_4_fu_456_p1 = kernel_size_read_reg_501;

always @ (posedge ap_clk) begin
    zext_ln1072_reg_568[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //im2col_mat
